<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBE6N60L\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBE6N60L/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBE6N60L.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBE6N60L\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBE6N60L\App_KernelDevDebugContainer([
    'container.build_hash' => 'BE6N60L',
    'container.build_id' => '096b320f',
    'container.build_time' => 1721296806,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBE6N60L');
